version: '3.8'

services:
  app:
    build: . # Build the app from the local Dockerfile
    environment:
      - SQL_USER=${SQL_USER}
      - SQL_HOST=jdbc:postgresql://ion-db:5432/${SQL_DATABASE}
      - SQL_PASSWORD=${SQL_PASSWORD}
      - STAGING_DIR=${STAGING_DIR}
      - TEMP_DIR=${TEMP_DIR}
      - CONFIG_FILE=${CONFIG_FILE}
      - GIT_SERVER_ADDRESS=${GIT_SERVER_ADDRESS}
      - GIT_REPOSITORY_NAME=${GIT_REPOSITORY_NAME}
      - GIT_USER=${GIT_USER}
      - GIT_PASSWORD=${GIT_PASSWORD}
      - GIT_BRANCH=${GIT_BRANCH}
      - SERVER_PORT=${SERVER_PORT}
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    depends_on:
      ion-db:
        condition: service_started
      git-setup:
        condition: service_started
  ion-db:
    image: postgres:13.2-alpine
    ports:
      - "${SQL_PORT}:5432"
    environment:
      - POSTGRES_USER=${SQL_USER}
      - POSTGRES_PASSWORD=${SQL_PASSWORD}
      - POSTGRES_DB=${SQL_DATABASE}
  git-server:
    image: gitbucket/gitbucket:4.35.3
    ports:
      - "${GIT_PORT}:8080"
    volumes:
      - git-data:/gitbucket
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:${GIT_PORT}" ]
      interval: 30s
      timeout: 10s
      retries: 5
  git-setup:
    image: gitbucket/gitbucket:4.35.3
    depends_on:
      git-server:
        condition: service_healthy
    restart: "no"
    entrypoint: [ "curl", "-X", "POST", "-u", "root:root", "git-server:${GIT_PORT}/api/v3/user/repos", "-d", "{\"name\":\"integration-data\", \"auto_init\": true}" ]
volumes:
  db-data:
  git-data: