name: I-On Integration Pull-Request

on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - 'docs/**'
      - '**/README.md'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build Docker image
        id: build_image
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: buildDockerImage -PonlyBuild=true
          gradle-version: 7.0
          wrapper-cache-enabled: true
          dependencies-cache-enabled: true
          configuration-cache-enabled: true