name: I-On Integration Pull-Request

on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - 'docs/**'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SQL_HOST: jdbc:postgresql://localhost:5432/pipeline
      SQL_USER: pipeline
      SQL_PASSWORD: pipeline

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: env.SQL_PASSWORD
          POSTGRES_USER: env.SQL_USER
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build Docker image
        id: build_image
        run: ./gradlew buildDockerImage -PonlyBuild=true
      
      - name: Publish Unit Test Results
        uses: docker://ghcr.io/enricomi/publish-unit-test-result-action:v1
        if: always()
        with:
          github_token: ${{ github.token }}
          files: test-results/**/*.xml