name: I-On Integration Production

on:
  push:
    tags:
      - v*

jobs:
  push_production:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && contains(github.ref, 'tags')

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build image
        id: production_build_image
        run: ./gradlew buildDockerImage