name: I-On Integration Pull-Request

on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - 'docs/**'
      - '**/README.md'

jobs:
  pr_integration:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup ACT test environment
        if: ${{ env.ACT }}
        run: curl https://cli-assets.heroku.com/install-ubuntu.sh | sh

      - name: Retrieve Database URL
        id: databaseUrl
        run: echo "::set-output name=url::$(heroku config:get DATABASE_URL -a ${{secrets.HEROKU_APP_NAME}})"
        env:
          HEROKU_API_KEY: ${{secrets.HEROKU_API_KEY}}

      - uses: rishabhgupta/split-by@v1
        id: split1
        with:
          string: ${{steps.databaseUrl.outputs.url}}
          split-by: '@'

      - uses: rishabhgupta/split-by@v1
        id: split2
        with:
          string: ${{steps.split1.outputs._0}}
          split-by: ':'

      - uses: rishabhgupta/split-by@v1
        id: split3
        with:
          string: ${{steps.split2.outputs._1}}
          split-by: '/'

      - uses: akhileshns/heroku-deploy@v3.12.12
        if: ${{ !env.ACT }}
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          usedocker: true
          docker_heroku_process_type: web
      - run: |
          echo "::add-mask::$HD_SQL_HOST"
          echo "::add-mask::$HD_SQL_USER"
          echo "::add-mask::$HD_SQL_PASSWORD"
        env:
          HD_SQL_HOST: jdbc:postgresql://${{ steps.split1.outputs._1}}
          HD_SQL_USER: ${{ steps.split3.outputs._2}}
          HD_SQL_PASSWORD: ${{ steps.split2.outputs._2}}
          HD_GIT_PORT: 443
          HD_STAGING_DIR: /app/staging
          HD_GIT_SERVER_ADDRESS: https://github.com/i-on-project/
          HD_GIT_REPOSITORY_NAME: integration-data
          HD_GIT_USER: ${{secrets.GIT_USER}}
          HD_GIT_PASSWORD: ""
          HD_GIT_BRANCH: staging

      - name: Print Environment Variables
        if: ${{ env.ACT }}
        run: |
          echo GIT_SERVER_ADDRESS=$GIT_SERVER_ADDRESS
          echo GIT_BRANCH=$GIT_BRANCH
