name: I-On Integration Staging

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'docs/**'

jobs:
  push_integration:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && contains(github.ref, 'heads')

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          usedocker: true
          docker_heroku_process_type: web
        env:
          SQL_HOST: ${{secrets.HEROKU_SQL_HOST}}/${{secrets.HEROKU_SQL_DATABASE}}?sslmode=require&user=${{secrets.HEROKU_SQL_USER}}&password=${{secrets.HEROKU_SQL_PASSWORD}}