name: I-On Integration Production

on:
  push:
    tags:
      - v*

jobs:
  push_production:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && contains(github.ref, 'tags')

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build Docker image
        id: build_image
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: buildDockerImage
          gradle-version: 6.8.3
          wrapper-cache-enabled: true
          dependencies-cache-enabled: true
          configuration-cache-enabled: true