name: I-On Integration Staging

on:
  push:
    branches:
      - master
    paths-ignore:
      - "docs/**"

jobs:
  push_integration:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && contains(github.ref, 'heads')

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "ion-integration-staging"
          heroku_email: "org.ionproject.integration@gmail.com"
          usedocker: true
