name: I-On Integration Production

on:
  push:
    tags:
      - v*

env:
  IMAGE_NAME: i-on-integration

jobs:
  push_production:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && contains(github.ref, 'tags')

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build image
        id: production_build_image
        env:
          SPRING_PROFILE: production
          GOOGLE_CLOUD_SQL_POSTGRES_USER: ${{ secrets.GOOGLE_CLOUD_SQL_POSTGRES_USER }}
          GOOGLE_CLOUD_SQL_POSTGRES_PASSWORD: ${{ secrets.GOOGLE_CLOUD_SQL_POSTGRES_PASSWORD }}
          ION_CORE_BASE_URL: ${{ secrets.ION_CORE_BASE_URL }}
          ION_CORE_TOKEN: ${{ secrets.ION_CORE_TOKEN }}
        run: ./gradlew buildDockerImage

      - name: Log into registry
        id: production_login_registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin

      - name: Push image
        id: production_push_image
        run: ./gradlew tagPushDockerImage -PgithubRef=${{ github.ref }}
