name: I-On Integration Staging

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'docs/**'

jobs:
  push_integration:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && contains(github.ref, 'heads')

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build image
        id: integration_build_image
        run: gradle buildDockerImage