name: I-On Integration Staging

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'docs/**'

env:
  IMAGE_NAME: i-on-integration

jobs:
  push_integration:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && contains(github.ref, 'heads')

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build image
        id: integration_build_image
        env:
          SPRING_PROFILE: staging
          GOOGLE_CLOUD_SQL_POSTGRES_USER: ${{ secrets.GOOGLE_CLOUD_SQL_POSTGRES_USER }}
          GOOGLE_CLOUD_SQL_POSTGRES_PASSWORD: ${{ secrets.GOOGLE_CLOUD_SQL_POSTGRES_PASSWORD }}
          ION_CORE_BASE_URL: ${{ secrets.ION_CORE_BASE_URL }}
          ION_CORE_TOKEN: ${{ secrets.ION_CORE_TOKEN }}
        run: ./gradlew buildDockerImage

      - name: Log into registry
        id: integration_login_registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin

      - name: Push image
        id: integration_push_image
        run: ./gradlew tagPushDockerImage
          