name: I-On Integration Staging

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'docs/**'

env:
  GCLOUD_PROJECT_ID: ${{ secrets.GOOGLE_CLOUD_PROJECT_ID }}

jobs:
  push_integration:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && contains(github.ref, 'heads')

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup gcloud CLI
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          project_id: $GCLOUD_PROJECT_ID
          service_account_key: ${{ secrets.GOOGLE_CLOUD_SERVICE_ACCOUNT_KEY }}

      - name: Gcloud as credential helper
        run: gcloud auth configure-docker

      - name: Build image
        id: integration_build_image
        run: ./gradlew buildDockerImage

      - name: Push image
        id: integration_push_image
        run: ./gradlew tagPushDockerImage

      - name: Deploy
        id: integration_deploy
        run: ./gradlew deploy
