name: I-On Integration Staging

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'docs/**'

jobs:
  push_integration:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && contains(github.ref, 'heads')

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build Docker image
        id: build_image
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: buildDockerImage
          gradle-version: 6.8.3
          wrapper-cache-enabled: true
          dependencies-cache-enabled: true
          configuration-cache-enabled: true