name: I-On Integration Production

on:
  push:
    tags:
      - v*

env:
  GCLOUD_PROJECT_ID: ${{ secrets.GOOGLE_CLOUD_PROJECT_ID }}

jobs:
  push_production:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && contains(github.ref, 'tags')

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup gcloud CLI
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GOOGLE_CLOUD_PROJECT_ID }}
          service_account_key: ${{ secrets.GOOGLE_CLOUD_SERVICE_ACCOUNT_KEY }}

      - name: Gcloud as credential helper
        run: gcloud auth configure-docker

      - name: Build image
        id: production_build_image
        env:
          SPRING_PROFILE: production
          GOOGLE_CLOUD_SQL_POSTGRES_USER: ${{ secrets.GOOGLE_CLOUD_SQL_POSTGRES_USER }}
          GOOGLE_CLOUD_SQL_POSTGRES_PASSWORD: ${{ secrets.GOOGLE_CLOUD_SQL_POSTGRES_PASSWORD }}
          ION_CORE_BASE_URL: ${{ secrets.ION_CORE_BASE_URL }}
          ION_CORE_TOKEN: ${{ secrets.ION_CORE_TOKEN }}
        run: ./gradlew buildDockerImage

      - name: Push image
        id: production_push_image
        run: ./gradlew tagPushDockerImage -PgithubRef=${{ github.ref }}

      - name: Deploy
        id: integration_deploy
        run: ./gradlew deploy -PgithubRef=${{ github.ref }}
