name: I-On Integration Pull-Request

on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - 'docs/**'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build Docker image
        id: build_image
        run: ./gradlew buildDockerImage -PonlyBuild=true