name: I-On Integration Pull-Request

on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - 'docs/**'
      - '**/README.md'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Run Linter and Unit Tests
        run: ./gradlew prebuild

      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "ion-integration-staging"
          heroku_email: "org.ionproject.integration@gmail.com"
          usedocker: true
