name: I-On Integration Staging

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'docs/**'

env:
  GCLOUD_PROJECT_ID: ${{ secrets.GOOGLE_CLOUD_PROJECT_ID }}

jobs:
  push_integration:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && contains(github.ref, 'heads')

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup gcloud CLI
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '270.0.0'
          service_account_email: ${{ secrets.GOOGLE_CLOUD_USER }}
          service_account_key: '${{ secrets.GOOGLE_CLOUD_PASSWORD }}'

      - name: Gcloud as credential helper
        run: gcloud auth configure-docker

      - name: Build image
        id: integration_build_image
        env:
          SPRING_PROFILE: staging
          GOOGLE_CLOUD_SQL_POSTGRES_USER: ${{ secrets.GOOGLE_CLOUD_SQL_POSTGRES_USER }}
          GOOGLE_CLOUD_SQL_POSTGRES_PASSWORD: ${{ secrets.GOOGLE_CLOUD_SQL_POSTGRES_PASSWORD }}
          ION_CORE_BASE_URL: ${{ secrets.ION_CORE_BASE_URL }}
          ION_CORE_TOKEN: ${{ secrets.ION_CORE_TOKEN }}
        run: ./gradlew buildDockerImage

      - name: Push image
        id: integration_push_image
        run: ./gradlew tagPushDockerImage

      - name: Deploy
        id: integration_deploy
        run: ./gradlew deploy
